require('user.options')
require('user.plugins')
require('user.lualine')
require('user.gitsigns')
require('user.telescope')
require('user.nvimtree')
require('user.bufferline')
require('user.treesitter')
require('user.comment')
require('user.autopairs')
require('user.diagnostics')
require('user.cmp')
require('user.nlsp')

local mappings = require('user.mappings')
require('user.lsp').setup(mappings.lsp_mappings)
require('user.null-ls').setup(mappings.lsp_mappings)
